version: "3"

services:

  ssr:
    image: orvice/shadowsocksr
    restart: always
    volumes:
      - ./ssr/config.json:/usr/src/app/config.json
      - ./log/ssr:/var/log/ssr
    env_file:
      - mu.env
    logging:
      driver: json-file
      options:
         max-size: "200k"
         max-file: "10"
    network_mode: host

  v2ray:
    image: v2ray/official
    restart: always
    volumes:
      - ./v2ray:/etc/v2ray
      - ./log/v2ray:/var/log/v2ray
    ports:
      - 8300:8300
      - 8300:8300/udp
    command: ["v2ray", "-config=/etc/v2ray/config.json"]


  v2ray-mu:
    image: orvice/v2ray-mu
    restart: always
    volumes:
      - ./log/v2ray-mu:/var/log/v2ray-mu
    logging:
      driver: json-file
      options:
         max-size: "200k"
         max-file: "10"
    env_file:
      - mu.env
 
  monitor-client:
    image: orvice/monitor-client
    restart: always
    volumes:
      - ./monitor_client_log:/var/log
    environment:
      - NET_INTERFACE=eth0
      - WEB_ADDR=:8080
      - GRPC_ADDR=:8090
    container_name: monitor-client
    network_mode: host

